#define GRID_BORDER_GAP 6
#define SQUARE_SIDE_LENGTH 30
#define SQUARE_GAP 3
#define NUM_SQUARE_PER_SIDE 7
#define SIDE_RECTANGLE_GAP 6
#define UP_UNDER_RECTANGLE_GAP 35
#define RECTANGLE_HORIZONTAL_SIDE_LENGTH 72
#define RECTANGLE_VERTICAL_SIDE_LENGTH 40
#define WALL_SLOTS_PER_SIDE 6
#define BOARD_LENGTH 13		// 7 squares + 6 gap for walls
#define MAX_NODES NUM_SQUARE_PER_SIDE*NUM_SQUARE_PER_SIDE
